// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Recette.WebApi.Data;

namespace Recette.WebApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Recette.WebApi.Models.Ingredient", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Ingredient");

                    b.HasData(
                        new
                        {
                            Id = "d3aaaff0-ad3d-403b-ae93-67964fb267e8",
                            Name = "pomme"
                        },
                        new
                        {
                            Id = "d3adaff0-ad3d-403b-ae93-67964fb267e8",
                            Name = "pâte brisée"
                        },
                        new
                        {
                            Id = "d3adaff0-ad3d-403b-af93-67964fb267e8",
                            Name = "sachet de sucre vanillé"
                        },
                        new
                        {
                            Id = "d3adaff0-ad3d-403b-ae93-67964fb267e9",
                            Name = "sucre"
                        });
                });

            modelBuilder.Entity("Recette.WebApi.Models.IngredientRecipe", b =>
                {
                    b.Property<string>("IngredientId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("RecipeId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("IngredientId", "RecipeId");

                    b.ToTable("IngredientRecipe");

                    b.HasData(
                        new
                        {
                            IngredientId = "d3aaaff0-ad3d-403b-ae93-67964fb267e8",
                            RecipeId = "d3aaaff0-ad3d-403b-ae93-67964fb267c8",
                            Quantity = 6,
                            Unit = "unit"
                        },
                        new
                        {
                            IngredientId = "d3adaff0-ad3d-403b-ae93-67964fb267e8",
                            RecipeId = "d3aaaff0-ad3d-403b-ae93-67964fb267c8",
                            Quantity = 1,
                            Unit = "unit"
                        },
                        new
                        {
                            IngredientId = "d3adaff0-ad3d-403b-af93-67964fb267e8",
                            RecipeId = "d3aaaff0-ad3d-403b-ae93-67964fb267c8",
                            Quantity = 1,
                            Unit = "unit"
                        },
                        new
                        {
                            IngredientId = "d3adaff0-ad3d-403b-ae93-67964fb267e9",
                            RecipeId = "d3aaaff0-ad3d-403b-ae93-67964fb267c8",
                            Quantity = 30,
                            Unit = "gramme"
                        });
                });

            modelBuilder.Entity("Recette.WebApi.Models.Recipe", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("ImageBase64")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("NumberOfPersons")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Recipe");

                    b.HasData(
                        new
                        {
                            Id = "d3aaaff0-ad3d-403b-ae93-67964fb267c8",
                            ImageBase64 = "",
                            Name = "Tarte aux pommes",
                            NumberOfPersons = 6
                        });
                });

            modelBuilder.Entity("Recette.WebApi.Models.Step", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("RecipeId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("Step");

                    b.HasData(
                        new
                        {
                            Id = "d3adaff0-ad3d-443b-ae93-67964fb267e1",
                            Description = "Éplucher et découper en morceaux 4 Golden.",
                            Number = 1,
                            RecipeId = "d3aaaff0-ad3d-403b-ae93-67964fb267c8"
                        },
                        new
                        {
                            Id = "d3adaff0-ad3d-443b-ae93-67964fb267e2",
                            Description = "Faire une compote : les mettre dans une casserole avec un peu d'eau (1 verre ou 2). Bien remuer. Quand les pommes commencent à ramollir, ajouter un sachet ou un sachet et demi de sucre vanillé. Ajouter un peu d'eau si nécessaire.",
                            Number = 2,
                            RecipeId = "d3aaaff0-ad3d-403b-ae93-67964fb267c8"
                        },
                        new
                        {
                            Id = "d3adaff0-ad3d-443b-ae93-67964fb267e4",
                            Description = "Vous saurez si la compote est prête une fois que les pommes ne seront plus dures du tout. Ce n'est pas grave s'il reste quelques morceaux.",
                            Number = 3,
                            RecipeId = "d3aaaff0-ad3d-403b-ae93-67964fb267c8"
                        },
                        new
                        {
                            Id = "d3adaff0-ad3d-443b-ae93-67964fb267e3",
                            Description = "Pendant que la compote cuit, éplucher et couper en quatre les deux dernières pommes, puis, couper les quartiers en fines lamelles (elles serviront à être posées sur la compote).",
                            Number = 4,
                            RecipeId = "d3aaaff0-ad3d-403b-ae93-67964fb267c8"
                        },
                        new
                        {
                            Id = "d3adaff0-ad3d-443b-ae93-67964fb267e5",
                            Description = "Préchauffer le four à 210°C (thermostat 7).",
                            Number = 5,
                            RecipeId = "d3aaaff0-ad3d-403b-ae93-67964fb267c8"
                        },
                        new
                        {
                            Id = "d3adaff0-ad3d-443b-ae93-67964fb267e6",
                            Description = "Laisser un peu refroidir la compote et étaler la pâte brisée dans un moule et la piquer avec une fourchette.",
                            Number = 6,
                            RecipeId = "d3aaaff0-ad3d-403b-ae93-67964fb267c8"
                        },
                        new
                        {
                            Id = "d3adaff0-ad3d-443b-ae93-67964fb267e7",
                            Description = "Verser la compote sur la pâte et placer les lamelles de pommes en formant une spirale ou plusieurs cercles, au choix ! Disposer des lamelles de beurre dessus.",
                            Number = 7,
                            RecipeId = "d3aaaff0-ad3d-403b-ae93-67964fb267c8"
                        },
                        new
                        {
                            Id = "d3adaff0-ad3d-443b-ae93-67964fb267e8",
                            Description = "Mettre au four et laisser cuire pendant 30 min max. Surveiller la cuisson. Vous pouvez ajouter un peu de sucre vanillé sur la tarte pendant que çà cuit pour caraméliser un peu.",
                            Number = 8,
                            RecipeId = "d3aaaff0-ad3d-403b-ae93-67964fb267c8"
                        });
                });

            modelBuilder.Entity("Recette.WebApi.Models.IngredientRecipe", b =>
                {
                    b.HasOne("Recette.WebApi.Models.Ingredient", "Ingredient")
                        .WithMany("IngredientRecipes")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Recette.WebApi.Models.Recipe", "Recipe")
                        .WithMany("IngredientRecipes")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Recette.WebApi.Models.Step", b =>
                {
                    b.HasOne("Recette.WebApi.Models.Recipe", "Recipe")
                        .WithMany("Steps")
                        .HasForeignKey("RecipeId");
                });
#pragma warning restore 612, 618
        }
    }
}
